<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DetailsController extends Controller
{
    public function detailsGermanium(){
        $history = "« Des forêts noires et un pays étrange, des habitants, simplement des barbares primitifs » L’historien romain TACTUS n’avait pas une opinion très flatteuse de la Germanie, la région à l’est du Rhin et au Nord du Danube. Au final, c’est cette qui donnera le nom a cet élément, un honneur que ne sera jamais fait aux Romains. Cette découverte est attribué au chimiste allemand Clemens Winkler qui le découvrit en 1886 en isolant le minéral argyrodite et qu’il l’a nommé ainsi, en raison de son amour pour sa patrie. Winkler réalisa une prédiction du chimiste russe Dimitri Mendeleev, qui développa la table périodique en 1871, et savait qu’il y avait un vide à remplir en dessous du silicone.";
        $property = "Le GERMANIUM compte parmi les Métaux Spéciaux les plus rares de la planète. L’élément aux reflets argentés fond à près de 1.000° C et boue à 2.820°C. le GER- MANIUM est un puissant semi-conducteur. Sa densité anormale étonne toujours et encore les scientifiques. En effet, la densité du GERMANIUM est plus faible à l’état solide qu’à l’état liquide. L’utilisation de ce Métal Spécial inerte est répandue, mais uniquement dans une concentration extrêmement faible. ";
        $application = "Pendant longtemps, il a été le métal le plus prisé dans l’électronique. Aujourd’hui, il est surtout utilisé dans les fibres optiques et optiques à infrarouge. Sans GER- MANIUM, il n’y aurait pas eu de câbles à fibre optique pour Internet. Les objectifs faits de GERMANIUM sont les seuls à ne pas laisser passer la lumière visible, mais laissent passer la lumière infra-rouge, par exemple dans les équipements de vision nocturne. Il est essen- tiel pour la production d’appareils à vision nocturne. De même qu’on fait souvent appel au GERMANIUM dans les semi-conducteurs, les bouteilles recyclables PET, les processeurs à haute performance, dans les détecteurs pour les rayonnements radioactifs et dans le photovol- taïque. Le GERMANIUM connait actuellement un boom au Japon dans l’industrie de la santé. SITUATION & PERSPECTIVES L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $situation = "L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $img = "avion-dysp.jpeg";
        return view('details', compact('history','property','application','situation','img'));
    }

    public function detailsindium(){
        $history = "Nous sommes en 1863. Lors de la Bataille de Gettysburg, les troupes des Etats du Nord et du Sud s’affrontent avec acharnement. Ce fut peut être le conflit le plus important de la guerre de Sécession, en tout cas l’un de ses plus sanglants. Après trois jours de fumée de fusils, de canons, et de rodomon- tades, 44.000 hommes se sont retirés du front à cause de leurs blessures. Les deux camps ont rapporté un total de près de 5.500 morts. De l’autre côté de l’Atlantique, dans la tranquille ville de Freiberg, deux chimistes allemands Ferdinand Reich et Theodor Richter loin de ces hostilités. Ils analysaient un échantillon contenant des traces de thallium et ils tombèrent sur une raie spectrale indigo de thallium. Ils réalisèrent vite qu’ils venaient de découvrir un nouvel élément : L‘INDIUM, nommé d‘après la ligne indigo de son spectre atomique, a été découvert par Ferdinand Reich et Hieronimus Theodor Richter en 1863 alors qu‘ils testaient des minerais de zinc avec un spec- trographe inventé par Robert Wilhelm Bunsen pour trouver du thallium. Richter réussit à isoler le mé- tal en 1867 et fut présenté au public pour la première fois à l’Exposition Universelle de Paris de 1867.";
        $property = "L’INDIUM est brillant et argenté est très mou à l’état pur. Vous pourriez y graver des formes ou l’entailler avec votre ongle. Mais il résiste lorsqu’il est plié. Les cristaux se désintègrent, se remettent en place tous seuls et produisent un grincement. Ils pleurent, au sens propre du terme comme les soldats blessés de Gettys- burg. L’INDIUM fond dès 156° C et il se transforme en gaz dès 2.080°C. ";
        $application = "Son usage commercial a commencé pendant la Se- conde Guerre Mondiale comme revêtement pour les paliers de moteurs d’avion. On le trouve aujourd’hui dans tous les écrans à cristaux liquides, les écrans tactiles, les iPhones, les écrans plats, les portables aussi bien que dans les ordinateurs et parmi les articles les plus populaire du 21e siècle. L’IN- DIUM ne sert pas qu’à la technologie des écrans, mais également sous forme de couche mince dans le pho- tovoltaïque (technologie de cellules photovoltaïques, en particulier dans le procédé CIGS à couche mince) et dans la nanotechnologie, dans lesquelles l’INDIUM tient un rôle significatif.  ";
        $situation = "Dès 2006, sur les 600 tonnes de production annuelle mondiale, 230 tonnes étaient nécessaires pour la production des écrans.
        Le renommé Institut Fraunhofer en Allemagne prévoit une augmentation de la demande annuelle a plus de 1.580 tonnes des 2030.
        Plus de cinquante pour cent de la production provient de Chine.
        Les plus grosses réserves mondiales s‘y trouvent également avec un gisement estime entre 8.000 et 11.000 tonnes selon les estimations.
        
        L’INDIUM est également répertorié dans la liste des Métaux Spéciaux du rapport* de la Commission Européenne, dont l’approvisionnement risque d’être problématique. ";
        $img = "pexels-pixabay-356036.jpg";
        return view('details', compact('history','property','application','situation','img'));
    }

    public function detailsdysprosium(){
        $history = "En 1886, celui qui découvrit le GALLIUM, Lecoq de Boisbaudran réussit un nou- veau coup de génie, celui d’isoler l’oxyde de DYSPROSIUM d’un échantillon d’oxyde d’Holmium, qu’on pensait jusqu’alors être une substance homogène. Le nom pro- vient du grec et signifie « difficilement accessible », ce qui le décrit parfaitement bien ";
        $property = "Ce métal lourd gris argenté est à la fois flexible et extensible. Il est très impur et de ce fait très réactif. En effet, il est oxydable à l’air libre; au contact de l’eau, il se dissout dans une fine acidité. Sous sa forme oxyde, c’est une poudre beige-jaune. Il coûtait un peu plus de 10 euros le kilogramme en 2003, contre plus de 320 en 2010.
        Tout comme le NÉODYME, le DYSPROSIUM possède des propriétés fortement magnétiques. Aussi le DYSPRO- SIUM fait-il partie des composants d’aimant perma- nents, qui sont utilisés dans des générateurs pour la production d’électricité et dans les voitures électriques. Il sert d’agent de protection pour les réacteurs nu- cléaires et les lampes à économie d’énergie. En outre, il entre dans la production de matériels pour les lasers, le verre, les lampes halogènes et CD. Dans l ́Aéronautique : On ajoute du DYSPROSIUM à des alliages de magnésium que l’on utilise dans l’aéronau- tique. Il augmente la dureté du matériau et facilite sa transformation. ";
        $application = "Pendant longtemps, il a été le métal le plus prisé dans l’électronique. Aujourd’hui, il est surtout utilisé dans les fibres optiques et optiques à infrarouge. Sans GER- MANIUM, il n’y aurait pas eu de câbles à fibre optique pour Internet. Les objectifs faits de GERMANIUM sont les seuls à ne pas laisser passer la lumière visible, mais laissent passer la lumière infra-rouge, par exemple dans les équipements de vision nocturne. Il est essen- tiel pour la production d’appareils à vision nocturne. De même qu’on fait souvent appel au GERMANIUM dans les semi-conducteurs, les bouteilles recyclables PET, les processeurs à haute performance, dans les détecteurs pour les rayonnements radioactifs et dans le photovol- taïque. Le GERMANIUM connait actuellement un boom au Japon dans l’industrie de la santé. SITUATION & PERSPECTIVES L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $situation = "Le DYSPROSIUM est une Terres rares lourde et La quan- tité actuelle exploitée du DYSPROSIUM est de moins de 100 tonnes par an. En raison de son rôle significatif, dû à sa résistance à la chaleur, pour les aimants perma- nents, le DYSPROSIUM appartient aux Terres Rares les plus importantes. En vertu de ces considérations, une forte augmentation de la demande en DYSPROSIUM est à prévoir.  ";
        $img = "avion-dysp.jpeg";
        return view('details', compact('history','property','application','situation','img'));
    }

    public function detailsgallium(){
        $history = "Nous sommes en 1875, Dans un petit laboratoire privé près du centre de Cognac, Une petite ville dans le Sud-Ouest de la France, à environ 120 kilomètres de Bordeaux célèbre pour son eau de vie fine. Le chimiste Paul Emile Lecoq de Boisbaudran travaille à la lumière clignotante de
        sa lampe à pétrole et est totalement absorbé par ses expériences. Il n’entend pas le cliquetis des calèches tirées par des chevaux, le bruit des gens plus bas, ni le chargement des tonneaux à vin complétement absorbé par les recherches sur un nouvel élément est sur le point de faire une dé- couverte sensationnelle: C’est un métal aux reflets bleu clair aux propriétés contradictoires rares, sans lequel, plus de 100 ans plus tard, nombres d’innovations technologiques n’auraient pas été rendues possibles. Cet élément sera appelé le GALLIUM. Le nom de De Boisbaudrans est pour toujours gravé dans l’histoire de la ville de Cognac pour cette découverte.";
        $property = "Le GERMANIUM compte parmi les Métaux Spéciaux les plus rares de la planète. L’élément aux reflets argentés fond à près de 1.000° C et boue à 2.820°C. le GER- MANIUM est un puissant semi-conducteur. Sa densité anormale étonne toujours et encore les scientifiques. En effet, la densité du GERMANIUM est plus faible à l’état solide qu’à l’état liquide. L’utilisation de ce Métal Spécial inerte est répandue, mais uniquement dans une concentration extrêmement faible. ";
        $application = "Le GALLIUM a de nombreux champs d’application : Au- jourd’hui, mélangé à de l’INDIUM et à l’étain, il devient un alliage appelé le galinstan qui est souvent utilisé dans les thermomètres depuis l’interdiction du

        mercure. La fabrication des semi-conducteurs est de nos jours la principale utilisation du GALLIUM. L’utili- sation du GALLIUM dans les semi-conducteurs aug- mente leur fonctionnalité de manière considérable en comparaison avec les technologies plus vieilles comme les semi-conducteurs à base de silicone. Il est présent dans le domaine mécanique de panneaux solaires, des appareils mobiles High Tech, tels que les ordinateurs et téléphones portables ou encore les consoles de jeux. Le GALLIUM brut se trouve également dans de nom- breux composants industriels et high tech, y compris dans les LED (diodes électroluminescentes).";
        $situation = "Etant donné la rareté du GALLIUM et de sa convoitise par l’industrie du High Tech, il fait partie des métaux, qui font l’objet d’un rapport*, publié en 2010 par la Commission Européenne, avançant des difficultés d’approvisionnement dans les années à venir. Rien que pour les LED, les experts s’attendent à une augmen- tation de l’utilisation du GALLIUM à une quantité bien supérieure à 100 tonnes à l’horizon 2012. Ceci devrait nettement contribuer à accentuer le problème de son approvisionnement. Dans l’ensemble, il faut s’attendre à une augmentation de la demande de 25%.";
        $img = "13625941VRZFH-france-gallium-cristal-400g.jpg";
        return view('details', compact('history','property','application','situation','img'));
    }
    public function detailsterbium(){
        $history = "Nous sommes en 1875, Dans un petit laboratoire privé près du centre de Cognac, Une petite ville dans le Sud-Ouest de la France, à environ 120 kilomètres de Bordeaux célèbre pour son eau de vie fine. Le chimiste Paul Emile Lecoq de Boisbaudran travaille à la lumière clignotante de
        sa lampe à pétrole et est totalement absorbé par ses expériences. Il n’entend pas le cliquetis des calèches tirées par des chevaux, le bruit des gens plus bas, ni le chargement des tonneaux à vin complétement absorbé par les recherches sur un nouvel élément est sur le point de faire une dé- couverte sensationnelle: C’est un métal aux reflets bleu clair aux propriétés contradictoires rares, sans lequel, plus de 100 ans plus tard, nombres d’innovations technologiques n’auraient pas été rendues possibles. Cet élément sera appelé le GALLIUM. Le nom de De Boisbaudrans est pour toujours gravé dans l’histoire de la ville de Cognac pour cette découverte.";
        $property = "Le GERMANIUM compte parmi les Métaux Spéciaux les plus rares de la planète. L’élément aux reflets argentés fond à près de 1.000° C et boue à 2.820°C. le GER- MANIUM est un puissant semi-conducteur. Sa densité anormale étonne toujours et encore les scientifiques. En effet, la densité du GERMANIUM est plus faible à l’état solide qu’à l’état liquide. L’utilisation de ce Métal Spécial inerte est répandue, mais uniquement dans une concentration extrêmement faible. ";
        $application = "Le GALLIUM a de nombreux champs d’application : Au- jourd’hui, mélangé à de l’INDIUM et à l’étain, il devient un alliage appelé le galinstan qui est souvent utilisé dans les thermomètres depuis l’interdiction du

        mercure. La fabrication des semi-conducteurs est de nos jours la principale utilisation du GALLIUM. L’utili- sation du GALLIUM dans les semi-conducteurs aug- mente leur fonctionnalité de manière considérable en comparaison avec les technologies plus vieilles comme les semi-conducteurs à base de silicone. Il est présent dans le domaine mécanique de panneaux solaires, des appareils mobiles High Tech, tels que les ordinateurs et téléphones portables ou encore les consoles de jeux. Le GALLIUM brut se trouve également dans de nom- breux composants industriels et high tech, y compris dans les LED (diodes électroluminescentes).";
        $situation = "Etant donné la rareté du GALLIUM et de sa convoitise par l’industrie du High Tech, il fait partie des métaux, qui font l’objet d’un rapport*, publié en 2010 par la Commission Européenne, avançant des difficultés d’approvisionnement dans les années à venir. Rien que pour les LED, les experts s’attendent à une augmen- tation de l’utilisation du GALLIUM à une quantité bien supérieure à 100 tonnes à l’horizon 2012. Ceci devrait nettement contribuer à accentuer le problème de son approvisionnement. Dans l’ensemble, il faut s’attendre à une augmentation de la demande de 25%.";
        $img = "avion-dysp.jpeg";
        return view('details', compact('history','property','application','situation','img'));
    }
    public function detailsneodyme(){
        $history = "« Des forêts noires et un pays étrange, des habitants, simplement des barbares primitifs » L’historien romain TACTUS n’avait pas une opinion très flatteuse de la Germanie, la région à l’est du Rhin et au Nord du Danube. Au final, c’est cette qui donnera le nom a cet élément, un honneur que ne sera jamais fait aux Romains. Cette découverte est attribué au chimiste allemand Clemens Winkler qui le découvrit en 1886 en isolant le minéral argyrodite et qu’il l’a nommé ainsi, en raison de son amour pour sa patrie. Winkler réalisa une prédiction du chimiste russe Dimitri Mendeleev, qui développa la table périodique en 1871, et savait qu’il y avait un vide à remplir en dessous du silicone.";
        $property = "Le néodyme, qui est bleu-violet sous forme d’oxyde, est plus résistant à la corrosion que les autres métaux des terres rares. Sa couche d’oxyde rose s’écaille facilement. Inhabituel : En tant que métal, il est hautement inflammable et irritant. Sa propriété exceptionnelle définit également son objectif principal : il est fortement magnétique.";
        $application = "Le néodyme est principalement utilisé pour fabriquer des aimants néodyme-fer-bore extrêmement puissants. Ceux-ci peuvent supporter en permanence 1 300 fois leur poids. Ils sont utilisés partout où des aimants puissants sont nécessaires dans de petits volumes : dans les éoliennes ou les moteurs électriques à haut rendement, dans les microphones ou les haut-parleurs des smartphones. En d’autres termes : dans l’ensemble de l’industrie high-tech.

        Les aimants en néodyme, par exemple, génèrent une puissance nettement plus élevée que les aimants conventionnels dans les générateurs d’éoliennes. Et comme le poids des unités joue un rôle majeur dans les éoliennes, le besoin en néodyme y est aussi de loin le plus élevé. 

        L’importance du néodyme pour de nombreuses technologies futures est ininterrompue et continue d’augmenter. 
        
        Par exemple, la technologie des ascenseurs du One World Trade Center à New York est basée sur des aimants en néodyme. 
        
        Les experts supposent que la demande mondiale de néodyme continuera d’augmenter.
        ";
        $situation = "L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $img = "neo.jpeg";
        return view('details', compact('history','property','application','situation','img'));
    }
    public function detailshafnium(){
        $history = "« Des forêts noires et un pays étrange, des habitants, simplement des barbares primitifs » L’historien romain TACTUS n’avait pas une opinion très flatteuse de la Germanie, la région à l’est du Rhin et au Nord du Danube. Au final, c’est cette qui donnera le nom a cet élément, un honneur que ne sera jamais fait aux Romains. Cette découverte est attribué au chimiste allemand Clemens Winkler qui le découvrit en 1886 en isolant le minéral argyrodite et qu’il l’a nommé ainsi, en raison de son amour pour sa patrie. Winkler réalisa une prédiction du chimiste russe Dimitri Mendeleev, qui développa la table périodique en 1871, et savait qu’il y avait un vide à remplir en dessous du silicone.";
        $property = "Le GERMANIUM compte parmi les Métaux Spéciaux les plus rares de la planète. L’élément aux reflets argentés fond à près de 1.000° C et boue à 2.820°C. le GER- MANIUM est un puissant semi-conducteur. Sa densité anormale étonne toujours et encore les scientifiques. En effet, la densité du GERMANIUM est plus faible à l’état solide qu’à l’état liquide. L’utilisation de ce Métal Spécial inerte est répandue, mais uniquement dans une concentration extrêmement faible. ";
        $application = "Pendant longtemps, il a été le métal le plus prisé dans l’électronique. Aujourd’hui, il est surtout utilisé dans les fibres optiques et optiques à infrarouge. Sans GER- MANIUM, il n’y aurait pas eu de câbles à fibre optique pour Internet. Les objectifs faits de GERMANIUM sont les seuls à ne pas laisser passer la lumière visible, mais laissent passer la lumière infra-rouge, par exemple dans les équipements de vision nocturne. Il est essen- tiel pour la production d’appareils à vision nocturne. De même qu’on fait souvent appel au GERMANIUM dans les semi-conducteurs, les bouteilles recyclables PET, les processeurs à haute performance, dans les détecteurs pour les rayonnements radioactifs et dans le photovol- taïque. Le GERMANIUM connait actuellement un boom au Japon dans l’industrie de la santé. SITUATION & PERSPECTIVES L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $situation = "L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $img = "avion-dysp.jpeg";
        return view('details', compact('history','property','application','situation','img'));
    }
    public function detailspraseodymium(){
        $history = "« Des forêts noires et un pays étrange, des habitants, simplement des barbares primitifs » L’historien romain TACTUS n’avait pas une opinion très flatteuse de la Germanie, la région à l’est du Rhin et au Nord du Danube. Au final, c’est cette qui donnera le nom a cet élément, un honneur que ne sera jamais fait aux Romains. Cette découverte est attribué au chimiste allemand Clemens Winkler qui le découvrit en 1886 en isolant le minéral argyrodite et qu’il l’a nommé ainsi, en raison de son amour pour sa patrie. Winkler réalisa une prédiction du chimiste russe Dimitri Mendeleev, qui développa la table périodique en 1871, et savait qu’il y avait un vide à remplir en dessous du silicone.";
        $property = "Le GERMANIUM compte parmi les Métaux Spéciaux les plus rares de la planète. L’élément aux reflets argentés fond à près de 1.000° C et boue à 2.820°C. le GER- MANIUM est un puissant semi-conducteur. Sa densité anormale étonne toujours et encore les scientifiques. En effet, la densité du GERMANIUM est plus faible à l’état solide qu’à l’état liquide. L’utilisation de ce Métal Spécial inerte est répandue, mais uniquement dans une concentration extrêmement faible. ";
        $application = "Pendant longtemps, il a été le métal le plus prisé dans l’électronique. Aujourd’hui, il est surtout utilisé dans les fibres optiques et optiques à infrarouge. Sans GER- MANIUM, il n’y aurait pas eu de câbles à fibre optique pour Internet. Les objectifs faits de GERMANIUM sont les seuls à ne pas laisser passer la lumière visible, mais laissent passer la lumière infra-rouge, par exemple dans les équipements de vision nocturne. Il est essen- tiel pour la production d’appareils à vision nocturne. De même qu’on fait souvent appel au GERMANIUM dans les semi-conducteurs, les bouteilles recyclables PET, les processeurs à haute performance, dans les détecteurs pour les rayonnements radioactifs et dans le photovol- taïque. Le GERMANIUM connait actuellement un boom au Japon dans l’industrie de la santé. SITUATION & PERSPECTIVES L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $situation = "L’heure est à l’épargne en ce qui concerne le GER- MANIUM. Seulement 140 tonnes sont produites par an dans le Monde, dont déjà 100 tonnes de ce métal convoité proviennent de la Chine. C’est la raison pour laquelle l’Empire du Milieu influence et contrôle le cours des prix. Le taux de recyclage a atteint entre-temps les 30%, tandis que les procédés restent extrêmement coûteux. Ceci signifie que le GERMANIUM est en voie de raréfaction. D’ailleurs, depuis, depuis 2005, il existe des difficultés dans l’approvisionnement du GERMANIUM ";
        $img = "avion-dysp.jpeg";
        return view('details', compact('history','property','application','situation','img'));
    }

}
